export const WORD_POOL = [
    "Ability", "Access", "Accident", "Account", "Act", "Action", "Activity", "Actor", "Ad", "Addition",
    "Address", "Administration", "Advantage", "Advertising", "Advice", "Affair", "Age", "Agency",
    "Agreement", "Air", "Airport", "Alcohol", "Ambition", "Amount", "Analysis", "Analyst", "Animal",
    "Answer", "Anxiety", "Apartment", "Appearance", "Apple", "Application", "Appointment", "Area",
    "Argument", "Army", "Arrival", "Art", "Article", "Aspect", "Assignment", "Assistance", "Assistant",
    "Association", "Assumption", "Atmosphere", "Attempt", "Attention", "Attitude", "Audience", "Aunt",
    "Average", "Awareness", "Back", "Bad", "Balance", "Ball", "Bank", "Baseball", "Basis", "Basket",
    "Bath", "Bathroom", "Bedroom", "Beer", "Beginning", "Benefit", "Bird", "Birth", "Birthday", "Bit",
    "Blood", "Board", "Boat", "Body", "Bonus", "Book", "Boss", "Bottom", "Contain", "Boy", "Boyfriend",
    "Bread", "Breath", "Brother", "Building", "Bus", "Business", "Buyer", "Cabinet", "Camera", "Cancer",
    "Candidate", "Capital", "Car", "Card", "Care", "Career", "Case", "Cash", "Feline", "Category", "Cause",
    "Celebration", "Cell", "Championship", "Chance", "Chapter", "Charity", "Cheek", "Chemistry", "Chest",
    "Chicken", "Child", "Wonder", "Chocolate", "Choice", "Church", "Cigarette", "City", "Class",
    "Classroom", "Client", "Climate", "Clothes", "Coast", "Coffee", "Collection", "College",
    "Combination", "Committee", "Communication", "Community", "Company", "Comparison", "Competition",
    "Complaint", "Computer", "Concept", "Conclusion", "Condition", "Confusion", "Connection",
    "Consequence", "Construction", "Contact", "Context", "Contract", "Contribution", "Control",
    "Conversation", "Cookie", "Country", "County", "Courage", "Course", "Cousin", "Craft", "Credit",
    "Criticism", "Culture", "Currency", "Shopping", "Cycle", "Dad", "Database", "Date", "Day",
    "Dealer", "Death", "Debt", "Decision", "Definition", "Delivery", "Demand", "Department", "Departure",
    "Depression", "Depth", "Description", "Design", "Desk", "Development", "Device", "Diamond",
    "Difference", "Difficulty", "Dinner", "Direction", "Director", "Dirt", "Disaster", "Discipline",
    "Discussion", "Disease", "Disk", "Widespread", "Wolf", "Drama", "Drawer", "Drawing", "Driver", "Ear",
    "Earth", "Measure", "Economy", "Editor", "Education", "Effect", "Efficiency", "Effort", "Egg",
    "Election", "Elevator", "Emotion", "Emphasis", "Employee", "Employer", "Employment", "End", "Energy",
    "Engine", "Entertainment", "Enthusiasm", "Entry", "Environment", "Equipment", "Error", "Establishment",
    "Estate", "Event", "Exam", "Examination", "Example", "Exchange", "Excitement", "Exercise", "Dismal",
    "Experience", "Explanation", "Expression", "Extent", "Eye", "Face", "Fact", "Failure", "Family",
    "Farmer", "Fat", "Feature", "Feedback", "Field", "Figure", "Film", "Finding", "Fire", "Scales", "Flight",
    "Focus", "Food", "Force", "Form", "Fortune", "Foundation", "Frame", "Freedom", "Fragrance",
    "Friendship", "Fun", "Funeral", "Future", "Game", "Garbage", "Garden", "Gate", "Gene", "Gift", "Girl",
    "Girlfriend", "Goal", "Government", "Grandmother", "Grocery", "Together", "Growth", "Guest", "Guidance",
    "Guide", "Guitar", "Style", "Half", "Hall", "Hand", "Hat", "Head", "Health", "Hearing", "Heart", "Heat",
    "Height", "Highway", "Historian", "History", "Outside", "Homework", "Hope", "Hospital", "Hotel",
    "Home", "Housing", "Ice", "Idea", "Image", "Imagination", "Impact", "Importance", "Impression",
    "Improvement", "Income", "Independence", "Indication", "Industry", "Inflation", "Information",
    "Initiative", "Injury", "Insect", "Inside", "Inspection", "Inspector", "Instance", "Instruction",
    "Insurance", "Intention", "Interaction", "Interest", "Internet", "Introduction", "Investment", "Issue",
    "Item", "Job", "Judgment", "Key", "Kind", "King", "Knowledge", "Lab", "Ladder", "Lady", "Lake",
    "Language", "Law", "Leader", "Leadership", "Length", "Level", "Library", "Life", "Light", "Line",
    "Link", "List", "Literature", "Location", "Loss", "Love", "Machine", "Magazine", "Maintenance", "Mall",
    "Man", "Management", "Manager", "Manufacturer", "Map", "Market", "Marketing", "Marriage", "Material",
    "Math", "Matter", "Meal", "Meaning", "Measurement", "Meat", "Media", "Medicine", "Medium", "Member",
    "Membership", "Memory", "Menu", "Message", "Metal", "Method", "Midnight", "Mind", "Mixture", "Mode",
    "Model", "Mom", "Moment", "Money", "Month", "Mood", "Morning", "Mouse", "Movie", "Mud", "Music",
    "Name", "Nation", "Nature", "Negotiation", "Network", "News", "Newspaper", "Night", "Note", "Nothing",
    "Number", "Object", "Obligation", "Office", "Oil", "Operation", "Opinion", "Opportunity", "Orange",
    "Order", "Organization", "Outcome", "Indoors", "Oven", "Owner", "Page", "Paint", "Painting", "Paper",
    "Part", "Passenger", "Passion", "Patience", "Payment", "Penalty", "Sculpture", "Drink", 
    "People", "Percentage", "Perception", "Performance", "Period", "Permission", "Person", "Personality",
    "Perspective", "Philosophy", "Phone", "Photo", "Physics", "Piano", "Artwork", "Pie", "Piece", "Pizza",
    "Place", "Plan", "Platform", "Player", "Poem", "Poet", "Poetry", "Point", "Police", "Policy", "Politics",
    "Pollution", "Population", "Position", "Possession", "Possibility", "Post", "Pot", "Potato", "Power",
    "Practice", "Preference", "Preparation", "Presence", "Presentation", "President", "Pressure", "Price",
    "Priority", "Problem", "Procedure", "Process", "Product", "Profession", "Professor", "Profit", "Program",
    "Promotion", "Property", "Proposal", "Protection", "Psychology", "Purpose", "Quality", "Quantity",
    "Queen", "Question", "Radio", "Range", "Rate", "Ratio", "Reaction", "False", "Reason", "Reception",
    "Recipe", "Recognition", "Recommendation", "Record", "Recording", "Reflection", "Refrigerator", "Region",
    "Relation", "Relationship", "Replacement", "Republic", "Reputation", "Requirement", "Research",
    "Resolution", "Resource", "Response", "Responsibility", "Restaurant", "Result", "Revenue", "Review",
    "Revolution", "Risk", "River", "Road", "Rock", "Role", "Room", "Rule", "Safety", "Salad", "Salt", "Sample",
    "Satiated", "Scale", "Scene", "Attendance", "Science", "Screen", "Secretary", "Section", "Sector",
    "Security", "Selection", "Sense", "Continuation", "Service", "Session", "Setting", "Shape", "Share", "Shirt",
    "Side", "Sign", "Signature", "Significance", "Singer", "Sir", "Sister", "Site", "Situation", "Size",
    "Skill", "Society", "Software", "Soil", "Solution", "Son", "Song", "Sound", "Soup", "Source", "Space",
    "Speaker", "Speech", "Sport", "Square", "Standard", "Star", "State", "Statement", "Steak", "Step",
    "Stock", "Storage", "Store", "Story", "Stranger", "Strategy", "Stress", "Structure", "Student", "Studio",
    "Study", "Dress", "Subject", "Success", "Suggestion", "Sun", "Supermarket", "Surgery", "Sympathy",
    "System", "Table", "Tale", "Task", "Tax", "Tea", "Teacher", "Technology", "Television", "Temperature",
    "Tennis", "Tension", "Term", "Test", "Thanks", "Theory", "Thing", "Thought", "Throat", "Time", "Tongue",
    "Tool", "Tooth", "Top", "Topic", "Town", "Trade", "Tradition", "Trainer", "Training", "Transportation",
    "Truth", "Two", "Type", "Uncle", "Understanding", "Union", "Unit", "University", "User", "Value",
    "Variation", "Variety", "Vehicle", "Version", "Video", "View", "Village", "Virus", "Voice", "Volume",
    "War", "Warning", "Water", "Way", "Weakness", "Wealth", "Weather", "Web", "Wedding", "Week", "While",
    "Wife", "Wind", "Winner", "Woman", "Wood", "Word", "Work", "Worker", "World", "Writer", "Writing",
    "Year", "Youth", "Sofa", "Aunt", "Ball", "Bermudas", "Beans", "Balloon", "Bear", "Blouse", "Bed",
    "Baby", "Book", "Blender", "Bucket", "Bakery", "Bow", "Bridge", "Boat", "Cow", "Cap", "Cooker",
    "Cheeks", "Crest", "Chest", "Chair", "Candy", "Counter", "Cat", "Soda", "Charlie", "Dog", "Deer",
    "Donkey", "Desktop", "Dentist", "Drum", "Dresser", "Designer", "Detective", "Frog", "Fan",
    "Freeze", "Fish", "Film", "Foot", "Flag", "Accomodate", "Hamburger", "Jewelry", "Awareness", "Awe", "Beauty",
    "Belief", "Childhood", "Clarity", "Cleverness", "Confusion", "Contentment", "Courage", "Crime", "Growth",
    "Happiness", "Hate", "Hatred", "Inflation", "Insanity", "Intelligence", "Joy", "Justice", "Kindness",
    "Laughter", "Law", "Liberty", "Love", "Luck", "Luxury", "Maturity", "Need", "Neglect",
    "Pain", "Principle", "Reality", "Relaxation", "Sanity", "Satisfaction", "Self-control", "Speed",
    "Strength", "Strictness", "Tiredness", "Tolerance", "Trend", "Removal", "Unreality", "Victory", "Wariness",
    "Warmth", "Prosperity", "Apple", "School", "Learning", "Picture", "House", "Tree", "Box", "Text", "Customer",
    "Friend", "Access", "Adulthood", "Alcohol", "Business", "Blood", "Botany", "Bacon", "Chaos", "Clothing",
    "Confidence", "Compassion", "Calm", "Cotton", "Danger", "Data", "Dancing", "Bookshelf", "Rug",
    "Distribution", "Dirt", "Duty", "Familiarity", "Economics", "Repairs", "Fame", "Glass",
    "Grass", "Golf", "Hair", "Hardware", "Hydrogen", "Hunger", "Honey", "Importance", "Waterfall",
    "Smart", "Industry", "Jealousy", "Jam", "Innocence", "Iron", "Linguistics", "Light", "Cruel", 
    "Loneliness", "Music", "Meat", "Nurture", "Mentality", "Herd", "Pack", "Flock", "Swarm", "Shoal",
    "Group", "Crowd", "Gang", "Mob", "Staff", "Crew", "Choir", "Orchestra", "Panel", "Board", "Troupe",
    "Bunch", "Pile", "Heap", "Set", "Stack", "Series", "Shower", "Fall", "Airline", "Airport", "Aircraft",
    "Armchair", "Boyfriend", "Battlefield", "Briefcase", "Butterfly", "Countdown", "Comeback", "Background",
    "Cupboard", "Chopstick", "Classmate", "Daredevil", "Daydream", "Dragonfly", "Everybody", "Everything",
    "Fireworks", "Football", "Footprint", "Greenhouse", "Hallway", "Handcuff", "Haircut", "Homework",
    "Horsefly", "Houseboat", "Moonlight", "Myself", "Notebook", "Overdue", "Pancake",
    "Partnership", "Photocopy", "Raincoat", "Rattlesnake", "Ringworm", "Skyscraper", "Sandcastle",
    "Snowboard", "Sunshine", "Teardrop", "Teacup", "Teapot", "Thunderstorm", "Timetable", "Yourself", "Rain",
]

export const generateThreeWords = () => {
    const selectedIndices = new Set();

    while (selectedIndices.size < 3) {
        const randIndex = Math.floor(Math.random() * WORD_POOL.length);
        selectedIndices.add(randIndex);
    }

    return Array.from(selectedIndices).map(index => WORD_POOL[index]);
};